######################
# CONFIGURATION FILE #
######################

slot:
    max_players: 32
    min_players: 2

game:
    # Durée en minute(s)
    duration: 5
    restart: true

arena:
    name:
    worldborder:
    world:
    size:
    center:
        x:
        y:
        z:
