######################
# CONFIGURATION FILE #
######################

slot:
    max_players: 32
    min_players: 2

arena:
    name:
    worldborder:
    world:
    size:
    center:
        x:
        y:
        z:
